name: videomamba

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1

num_monocular_samples: 32
num_surfaces: 1
predict_opacity: false

gaussians_per_pixel: 1

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4

d_feature: 128

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false

apply_bounds_shim: true

gs_params_head_type: dpt-video # -> sole head (static) -> 只编码我指定的车辆bbox，与VideoMamba输出的特征做CrossAttention
# dpt-video-hierarchical -> static head + dynamic head
pose_free: true
pretrained_weights: ""

mamba_choice: "base"
num_frames: 20
seed: 32768
dec_embed_dim: 768
dec_depth: 12
dec_num_heads: 16
mlp_ratio: 4,
norm_im2_in_dec: true
pos_embed: "cosine"