defaults:
  - base_dataset
  - view_sampler: bounded
  - optional view_sampler_dataset_specific_config@view_sampler: bounded_point_odyssey

# src/dataset/view_sampler/__init__.py
# 8:      from .view_sampler_bounded import ViewSamplerBounded, ViewSamplerBoundedCfg
# 14:    "bounded": ViewSamplerBounded,

name: point_odyssey # wandb.name
roots: [datasets/point_odyssey]

input_image_shape: [216, 384]
original_image_shape: [540, 960]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e10
max_fov: 100.0

dataset_location: ./datasets/point_odyssey

graph:
  use_augs: False
  S: 2
  N: 16
  strides: [1,2,3,4,5,6,7,8,9] # t+1,t+2,...,t+9
  clip_step: 2
  quick: False
  verbose: False
  dist_type: None
  clip_step_last_skip: 0
